# coding: utf-8

"""
    Clash of Clans API

    Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\".   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.leagues_api import LeaguesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLeaguesApi(unittest.TestCase):
    """LeaguesApi unit test stubs"""

    def setUp(self):
        self.api = LeaguesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_builder_base_league(self):
        """Test case for get_builder_base_league

        Get Builder Base league information  # noqa: E501
        """
        pass

    def test_get_builder_base_leagues(self):
        """Test case for get_builder_base_leagues

        List Builder Base leagues  # noqa: E501
        """
        pass

    def test_get_capital_league(self):
        """Test case for get_capital_league

        Get capital league information  # noqa: E501
        """
        pass

    def test_get_capital_leagues(self):
        """Test case for get_capital_leagues

        List capital leagues  # noqa: E501
        """
        pass

    def test_get_league(self):
        """Test case for get_league

        Get league information  # noqa: E501
        """
        pass

    def test_get_league_season_rankings(self):
        """Test case for get_league_season_rankings

        Get league season rankings  # noqa: E501
        """
        pass

    def test_get_league_seasons(self):
        """Test case for get_league_seasons

        Get league seasons  # noqa: E501
        """
        pass

    def test_get_leagues(self):
        """Test case for get_leagues

        List leagues  # noqa: E501
        """
        pass

    def test_get_war_league(self):
        """Test case for get_war_league

        Get war league information  # noqa: E501
        """
        pass

    def test_get_war_leagues(self):
        """Test case for get_war_leagues

        List war leagues  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
