# coding: utf-8

"""
    Clash of Clans API

    Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\".   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.clans_api import ClansApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClansApi(unittest.TestCase):
    """ClansApi unit test stubs"""

    def setUp(self):
        self.api = ClansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_capital_raid_seasons(self):
        """Test case for get_capital_raid_seasons

        Retrieve clan's capital raid seasons  # noqa: E501
        """
        pass

    def test_get_clan(self):
        """Test case for get_clan

        Get clan information  # noqa: E501
        """
        pass

    def test_get_clan_members(self):
        """Test case for get_clan_members

        List clan members  # noqa: E501
        """
        pass

    def test_get_clan_war_league_group(self):
        """Test case for get_clan_war_league_group

        Retrieve information about clan's current clan war league group  # noqa: E501
        """
        pass

    def test_get_clan_war_league_war(self):
        """Test case for get_clan_war_league_war

        Retrieve information about individual clan war league war  # noqa: E501
        """
        pass

    def test_get_clan_war_log(self):
        """Test case for get_clan_war_log

        Retrieve clan's clan war log  # noqa: E501
        """
        pass

    def test_get_current_war(self):
        """Test case for get_current_war

        Retrieve information about clan's current clan war  # noqa: E501
        """
        pass

    def test_search_clans(self):
        """Test case for search_clans

        Search clans  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
