# coding: utf-8

"""
    Clash of Clans API

    Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\".   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.locations_api import LocationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_clan_builder_base_ranking(self):
        """Test case for get_clan_builder_base_ranking

        Get clan Builder Base rankings for a specific location  # noqa: E501
        """
        pass

    def test_get_clan_capital_ranking(self):
        """Test case for get_clan_capital_ranking

        Get capital rankings for a specific location  # noqa: E501
        """
        pass

    def test_get_clan_ranking(self):
        """Test case for get_clan_ranking

        Get clan rankings for a specific location  # noqa: E501
        """
        pass

    def test_get_location(self):
        """Test case for get_location

        Get location information  # noqa: E501
        """
        pass

    def test_get_locations(self):
        """Test case for get_locations

        List locations  # noqa: E501
        """
        pass

    def test_get_player_builder_base_ranking(self):
        """Test case for get_player_builder_base_ranking

        Get player Builder Base rankings for a specific location  # noqa: E501
        """
        pass

    def test_get_player_ranking(self):
        """Test case for get_player_ranking

        Get player rankings for a specific location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
