# coding: utf-8

"""
    Clash of Clans API

    Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\".   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Clash of Clans API",
    author_email="",
    url="",
    keywords=["Swagger", "Clash of Clans API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Check out &lt;a href&#x3D;\&quot;https://developer.clashofclans.com/#/getting-started\&quot; target&#x3D;\&quot;_parent\&quot;&gt;Getting Started&lt;/a&gt; for instructions and links to other resources. Clash of Clans API uses &lt;a href&#x3D;\&quot;https://jwt.io/\&quot; target&#x3D;\&quot;_blank\&quot;&gt;JSON Web Tokens&lt;/a&gt; for authorizing the requests. Tokens are created by developers on &lt;a href&#x3D;\&quot;https://developer.clashofclans.com/#/account\&quot; target&#x3D;\&quot;_parent\&quot;&gt;My Account&lt;/a&gt; page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \&quot;Authorization: Bearer API_TOKEN\&quot;.   # noqa: E501
    """
)
