# coding: utf-8

"""
    Clash of Clans API

    Clash of Clans API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClanWarLeagueRound(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'war_tags': 'StringList'
    }

    attribute_map = {
        'war_tags': 'warTags'
    }

    def __init__(self, war_tags=None):  # noqa: E501
        """ClanWarLeagueRound - a model defined in Swagger"""  # noqa: E501
        self._war_tags = None
        self.discriminator = None
        if war_tags is not None:
            self.war_tags = war_tags

    @property
    def war_tags(self):
        """Gets the war_tags of this ClanWarLeagueRound.  # noqa: E501


        :return: The war_tags of this ClanWarLeagueRound.  # noqa: E501
        :rtype: StringList
        """
        return self._war_tags

    @war_tags.setter
    def war_tags(self, war_tags):
        """Sets the war_tags of this ClanWarLeagueRound.


        :param war_tags: The war_tags of this ClanWarLeagueRound.  # noqa: E501
        :type: StringList
        """

        self._war_tags = war_tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClanWarLeagueRound, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClanWarLeagueRound):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
