# coding: utf-8

"""
    Clash of Clans API

    Clash of Clans API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClanDistrictData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'district_hall_level': 'int',
        'id': 'int',
        'name': 'JsonLocalizedName'
    }

    attribute_map = {
        'district_hall_level': 'districtHallLevel',
        'id': 'id',
        'name': 'name'
    }

    def __init__(self, district_hall_level=None, id=None, name=None):  # noqa: E501
        """ClanDistrictData - a model defined in Swagger"""  # noqa: E501
        self._district_hall_level = None
        self._id = None
        self._name = None
        self.discriminator = None
        if district_hall_level is not None:
            self.district_hall_level = district_hall_level
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name

    @property
    def district_hall_level(self):
        """Gets the district_hall_level of this ClanDistrictData.  # noqa: E501


        :return: The district_hall_level of this ClanDistrictData.  # noqa: E501
        :rtype: int
        """
        return self._district_hall_level

    @district_hall_level.setter
    def district_hall_level(self, district_hall_level):
        """Sets the district_hall_level of this ClanDistrictData.


        :param district_hall_level: The district_hall_level of this ClanDistrictData.  # noqa: E501
        :type: int
        """

        self._district_hall_level = district_hall_level

    @property
    def id(self):
        """Gets the id of this ClanDistrictData.  # noqa: E501


        :return: The id of this ClanDistrictData.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ClanDistrictData.


        :param id: The id of this ClanDistrictData.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ClanDistrictData.  # noqa: E501


        :return: The name of this ClanDistrictData.  # noqa: E501
        :rtype: JsonLocalizedName
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ClanDistrictData.


        :param name: The name of this ClanDistrictData.  # noqa: E501
        :type: JsonLocalizedName
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClanDistrictData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClanDistrictData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
