# coding: utf-8

"""
    Clash of Clans API

    Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\".   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClanRanking(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'clan_level': 'int',
        'clan_points': 'int',
        'location': 'Location',
        'members': 'int',
        'tag': 'str',
        'name': 'str',
        'rank': 'int',
        'previous_rank': 'int',
        'badge_urls': 'object'
    }

    attribute_map = {
        'clan_level': 'clanLevel',
        'clan_points': 'clanPoints',
        'location': 'location',
        'members': 'members',
        'tag': 'tag',
        'name': 'name',
        'rank': 'rank',
        'previous_rank': 'previousRank',
        'badge_urls': 'badgeUrls'
    }

    def __init__(self, clan_level=None, clan_points=None, location=None, members=None, tag=None, name=None, rank=None, previous_rank=None, badge_urls=None):  # noqa: E501
        """ClanRanking - a model defined in Swagger"""  # noqa: E501
        self._clan_level = None
        self._clan_points = None
        self._location = None
        self._members = None
        self._tag = None
        self._name = None
        self._rank = None
        self._previous_rank = None
        self._badge_urls = None
        self.discriminator = None
        if clan_level is not None:
            self.clan_level = clan_level
        if clan_points is not None:
            self.clan_points = clan_points
        if location is not None:
            self.location = location
        if members is not None:
            self.members = members
        if tag is not None:
            self.tag = tag
        if name is not None:
            self.name = name
        if rank is not None:
            self.rank = rank
        if previous_rank is not None:
            self.previous_rank = previous_rank
        if badge_urls is not None:
            self.badge_urls = badge_urls

    @property
    def clan_level(self):
        """Gets the clan_level of this ClanRanking.  # noqa: E501


        :return: The clan_level of this ClanRanking.  # noqa: E501
        :rtype: int
        """
        return self._clan_level

    @clan_level.setter
    def clan_level(self, clan_level):
        """Sets the clan_level of this ClanRanking.


        :param clan_level: The clan_level of this ClanRanking.  # noqa: E501
        :type: int
        """

        self._clan_level = clan_level

    @property
    def clan_points(self):
        """Gets the clan_points of this ClanRanking.  # noqa: E501


        :return: The clan_points of this ClanRanking.  # noqa: E501
        :rtype: int
        """
        return self._clan_points

    @clan_points.setter
    def clan_points(self, clan_points):
        """Sets the clan_points of this ClanRanking.


        :param clan_points: The clan_points of this ClanRanking.  # noqa: E501
        :type: int
        """

        self._clan_points = clan_points

    @property
    def location(self):
        """Gets the location of this ClanRanking.  # noqa: E501


        :return: The location of this ClanRanking.  # noqa: E501
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this ClanRanking.


        :param location: The location of this ClanRanking.  # noqa: E501
        :type: Location
        """

        self._location = location

    @property
    def members(self):
        """Gets the members of this ClanRanking.  # noqa: E501


        :return: The members of this ClanRanking.  # noqa: E501
        :rtype: int
        """
        return self._members

    @members.setter
    def members(self, members):
        """Sets the members of this ClanRanking.


        :param members: The members of this ClanRanking.  # noqa: E501
        :type: int
        """

        self._members = members

    @property
    def tag(self):
        """Gets the tag of this ClanRanking.  # noqa: E501


        :return: The tag of this ClanRanking.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ClanRanking.


        :param tag: The tag of this ClanRanking.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def name(self):
        """Gets the name of this ClanRanking.  # noqa: E501


        :return: The name of this ClanRanking.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ClanRanking.


        :param name: The name of this ClanRanking.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def rank(self):
        """Gets the rank of this ClanRanking.  # noqa: E501


        :return: The rank of this ClanRanking.  # noqa: E501
        :rtype: int
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """Sets the rank of this ClanRanking.


        :param rank: The rank of this ClanRanking.  # noqa: E501
        :type: int
        """

        self._rank = rank

    @property
    def previous_rank(self):
        """Gets the previous_rank of this ClanRanking.  # noqa: E501


        :return: The previous_rank of this ClanRanking.  # noqa: E501
        :rtype: int
        """
        return self._previous_rank

    @previous_rank.setter
    def previous_rank(self, previous_rank):
        """Sets the previous_rank of this ClanRanking.


        :param previous_rank: The previous_rank of this ClanRanking.  # noqa: E501
        :type: int
        """

        self._previous_rank = previous_rank

    @property
    def badge_urls(self):
        """Gets the badge_urls of this ClanRanking.  # noqa: E501


        :return: The badge_urls of this ClanRanking.  # noqa: E501
        :rtype: object
        """
        return self._badge_urls

    @badge_urls.setter
    def badge_urls(self, badge_urls):
        """Sets the badge_urls of this ClanRanking.


        :param badge_urls: The badge_urls of this ClanRanking.  # noqa: E501
        :type: object
        """

        self._badge_urls = badge_urls

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClanRanking, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClanRanking):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
