# coding: utf-8

"""
    Clash of Clans API

    Clash of Clans API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClanBuilderBaseRanking(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'clan_builder_base_points': 'int',
        'clan_points': 'int'
    }

    attribute_map = {
        'clan_builder_base_points': 'clanBuilderBasePoints',
        'clan_points': 'clanPoints'
    }

    def __init__(self, clan_builder_base_points=None, clan_points=None):  # noqa: E501
        """ClanBuilderBaseRanking - a model defined in Swagger"""  # noqa: E501
        self._clan_builder_base_points = None
        self._clan_points = None
        self.discriminator = None
        if clan_builder_base_points is not None:
            self.clan_builder_base_points = clan_builder_base_points
        if clan_points is not None:
            self.clan_points = clan_points

    @property
    def clan_builder_base_points(self):
        """Gets the clan_builder_base_points of this ClanBuilderBaseRanking.  # noqa: E501


        :return: The clan_builder_base_points of this ClanBuilderBaseRanking.  # noqa: E501
        :rtype: int
        """
        return self._clan_builder_base_points

    @clan_builder_base_points.setter
    def clan_builder_base_points(self, clan_builder_base_points):
        """Sets the clan_builder_base_points of this ClanBuilderBaseRanking.


        :param clan_builder_base_points: The clan_builder_base_points of this ClanBuilderBaseRanking.  # noqa: E501
        :type: int
        """

        self._clan_builder_base_points = clan_builder_base_points

    @property
    def clan_points(self):
        """Gets the clan_points of this ClanBuilderBaseRanking.  # noqa: E501


        :return: The clan_points of this ClanBuilderBaseRanking.  # noqa: E501
        :rtype: int
        """
        return self._clan_points

    @clan_points.setter
    def clan_points(self, clan_points):
        """Sets the clan_points of this ClanBuilderBaseRanking.


        :param clan_points: The clan_points of this ClanBuilderBaseRanking.  # noqa: E501
        :type: int
        """

        self._clan_points = clan_points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClanBuilderBaseRanking, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClanBuilderBaseRanking):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
