# coding: utf-8

"""
    Clash of Clans API

    Clash of Clans API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClanCapitalRaidSeasonAttack(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attacker': 'ClanCapitalRaidSeasonAttacker',
        'destruction_percent': 'int',
        'stars': 'int'
    }

    attribute_map = {
        'attacker': 'attacker',
        'destruction_percent': 'destructionPercent',
        'stars': 'stars'
    }

    def __init__(self, attacker=None, destruction_percent=None, stars=None):  # noqa: E501
        """ClanCapitalRaidSeasonAttack - a model defined in Swagger"""  # noqa: E501
        self._attacker = None
        self._destruction_percent = None
        self._stars = None
        self.discriminator = None
        if attacker is not None:
            self.attacker = attacker
        if destruction_percent is not None:
            self.destruction_percent = destruction_percent
        if stars is not None:
            self.stars = stars

    @property
    def attacker(self):
        """Gets the attacker of this ClanCapitalRaidSeasonAttack.  # noqa: E501


        :return: The attacker of this ClanCapitalRaidSeasonAttack.  # noqa: E501
        :rtype: ClanCapitalRaidSeasonAttacker
        """
        return self._attacker

    @attacker.setter
    def attacker(self, attacker):
        """Sets the attacker of this ClanCapitalRaidSeasonAttack.


        :param attacker: The attacker of this ClanCapitalRaidSeasonAttack.  # noqa: E501
        :type: ClanCapitalRaidSeasonAttacker
        """

        self._attacker = attacker

    @property
    def destruction_percent(self):
        """Gets the destruction_percent of this ClanCapitalRaidSeasonAttack.  # noqa: E501


        :return: The destruction_percent of this ClanCapitalRaidSeasonAttack.  # noqa: E501
        :rtype: int
        """
        return self._destruction_percent

    @destruction_percent.setter
    def destruction_percent(self, destruction_percent):
        """Sets the destruction_percent of this ClanCapitalRaidSeasonAttack.


        :param destruction_percent: The destruction_percent of this ClanCapitalRaidSeasonAttack.  # noqa: E501
        :type: int
        """

        self._destruction_percent = destruction_percent

    @property
    def stars(self):
        """Gets the stars of this ClanCapitalRaidSeasonAttack.  # noqa: E501


        :return: The stars of this ClanCapitalRaidSeasonAttack.  # noqa: E501
        :rtype: int
        """
        return self._stars

    @stars.setter
    def stars(self, stars):
        """Sets the stars of this ClanCapitalRaidSeasonAttack.


        :param stars: The stars of this ClanCapitalRaidSeasonAttack.  # noqa: E501
        :type: int
        """

        self._stars = stars

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClanCapitalRaidSeasonAttack, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClanCapitalRaidSeasonAttack):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
